name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake contribution graph
        uses: Platane/snk@v3
        with:
          github_user_name: GiuseppeGambardella
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          commit_message: "generate snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
